# Generated by Django 5.1.3 on 2024-11-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
